import { getCurrentUser } from "@/lib/auth/session";
import { canWrite } from "@/lib/constants/roles";
import { PageHeader } from "@/components/ui/page-header";
import { LinkButton } from "@/components/ui/button";
import { InventoryTabs } from "./inventory-tabs";

export default async function InventoryTabsLayout({ children }: { children: React.ReactNode }) {
  const user = await getCurrentUser();
  const canRecordWastage = canWrite(user?.roles ?? [], "inventory");

  return (
    <div>
      <PageHeader
        title="Inventory Ledger"
        description="Read-only, append-only log generated by Purchase, QC, Finished Product and Packaging. Recording wastage is the one write this screen owns."
        action={
          canRecordWastage ? (
            <LinkButton href="/inventory/wastage/new" variant="danger">
              Record wastage
            </LinkButton>
          ) : undefined
        }
      />
      <InventoryTabs />
      {children}
    </div>
  );
}
