"use client";

import { useState } from "react";
import { Textarea } from "@/components/ui/form";
import { Button } from "@/components/ui/button";
import { Trash2, Plus } from "lucide-react";
import type { EditableTemplateLine } from "@/lib/actions/coa-templates";

// Same client-side add/remove-only pattern as MfrProcedureEditor
// (app/(dashboard)/mfr/mfr-procedure-editor.tsx) — Ravi explicitly asked
// for this ("Serial number will be autogenerated, similar to
// Manufacturing Process entry form in MFR"). S.No. isn't a field here:
// it's just each row's position, assigned server-side as `seq` in
// upsert_coa_template() (0059_coa_templates.sql).
export function CoaTemplateLineEditor({ initialLines }: { initialLines?: EditableTemplateLine[] }) {
  const [lines, setLines] = useState<EditableTemplateLine[]>(
    initialLines && initialLines.length > 0 ? initialLines : [{ test: "", specification: "" }]
  );

  function addLine() {
    setLines((ls) => [...ls, { test: "", specification: "" }]);
  }
  function removeLine(i: number) {
    setLines((ls) => (ls.length === 1 ? ls : ls.filter((_, idx) => idx !== i)));
  }
  function updateLine(i: number, patch: Partial<EditableTemplateLine>) {
    setLines((ls) => ls.map((l, idx) => (idx === i ? { ...l, ...patch } : l)));
  }

  return (
    <div className="flex flex-col gap-3">
      <input type="hidden" name="lineCount" value={lines.length} />
      <div className="rounded-md border border-border overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border bg-black/[0.02] text-left text-xs font-semibold uppercase tracking-wide text-muted">
              <th className="px-3 py-2 w-10">S.N.</th>
              <th className="px-3 py-2 w-64">Test</th>
              <th className="px-3 py-2">Specification</th>
              <th className="px-3 py-2 w-10" />
            </tr>
          </thead>
          <tbody>
            {lines.map((line, i) => (
              <tr key={i} className="border-b border-border last:border-0 align-top">
                <td className="px-3 py-2.5 text-muted">{i + 1}.</td>
                <td className="px-3 py-2">
                  <Textarea
                    name={`test_${i}`}
                    rows={2}
                    value={line.test}
                    onChange={(e) => updateLine(i, { test: e.target.value })}
                    placeholder="e.g. Loss on drying"
                    required={i === 0}
                  />
                </td>
                <td className="px-3 py-2">
                  <Textarea
                    name={`specification_${i}`}
                    rows={2}
                    value={line.specification}
                    onChange={(e) => updateLine(i, { specification: e.target.value })}
                    placeholder="e.g. Not More Than 10 %w/w"
                    required={i === 0}
                  />
                </td>
                <td className="px-3 py-2">
                  <button
                    type="button"
                    onClick={() => removeLine(i)}
                    className="text-muted hover:text-red disabled:opacity-30"
                    disabled={lines.length === 1}
                    aria-label="Remove row"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div>
        <Button type="button" variant="secondary" size="sm" onClick={addLine}>
          <Plus className="h-4 w-4" /> Add test
        </Button>
      </div>
    </div>
  );
}
