// Who is signed in, for the "Generated by" line printed on PDFs. The name is
// set once by <PdfUserSetter /> (components/shell/pdf-user-setter.tsx) when the
// dashboard loads, so every PDF helper can read it without each screen
// passing it down.
let currentName: string | null = null;

export function setPdfUser(name: string | null) {
  currentName = name && name.trim() ? name.trim() : null;
}

export function getPdfUser(): string | null {
  return currentName;
}
