import { COMPANY_NAME } from "@/lib/company";
import { getPdfUser } from "@/lib/pdf-user";
import { formatDate, formatDateTime, formatNumber, todayIst } from "@/lib/utils";

// Export of a list's rows to Excel or PDF (29 Sept 2026, export decision (c),
// Ravi). A list opts in by giving its table a TableExport; the table then
// shows Excel / PDF buttons that export the rows currently on screen (after
// the search box and "Hide legacy data"), not just the visible page.

export type ExportColumnType = "text" | "number" | "date" | "datetime";

export type ExportColumn<T> = {
  header: string;
  // Raw value: a number for quantities and money (so Excel can add it up), an
  // ISO date / timestamp string for dates, text otherwise.
  value: (row: T) => string | number | null | undefined;
  type?: ExportColumnType; // default "text"
  // Number columns: most decimals to show (default 2). Trailing zeros trimmed
  // on PDF, like everywhere else in the app.
  decimals?: number;
};

export type ExportFormat = "excel" | "pdf";

export type TableExport<T> = {
  // Names the sheet / PDF title, e.g. "Item Master".
  title: string;
  // File name without extension or date, e.g. "item-master".
  filename: string;
  columns: ExportColumn<T>[];
  formats: ExportFormat[];
  // Optional extra line for the "About this export" sheet and the PDF, e.g.
  // that a list is capped.
  note?: string;
};

export type ExportContext = {
  search: string;
  hideLegacy: boolean;
  // Replaces the automatic "Search … / Legacy data …" description, for lists
  // whose filters are something else (e.g. the Reports date range).
  filterText?: string;
};

function describeFilter(ctx: ExportContext, note?: string): string {
  if (ctx.filterText) return note ? `${ctx.filterText} · ${note}` : ctx.filterText;
  const parts = [ctx.search.trim() ? `Search: "${ctx.search.trim()}"` : "No search filter"];
  parts.push(ctx.hideLegacy ? "Legacy data hidden" : "Legacy data shown");
  if (note) parts.push(note);
  return parts.join(" · ");
}

// Cell text for a PDF (and the fallback everywhere text is needed).
export function exportCellText<T>(col: ExportColumn<T>, row: T): string {
  const v = col.value(row);
  if (v === null || v === undefined || v === "") return "—";
  switch (col.type) {
    case "number":
      return formatNumber(v as number | string, col.decimals ?? 2);
    case "date":
      return formatDate(String(v));
    case "datetime":
      return formatDateTime(String(v));
    default:
      return String(v);
  }
}

export async function exportTable<T>(
  cfg: TableExport<T>,
  format: ExportFormat,
  rows: T[],
  ctx: ExportContext
): Promise<void> {
  const stamp = todayIst();
  if (format === "pdf") {
    // Loaded on demand so the PDF library isn't part of every page.
    const { downloadPdfTable } = await import("@/lib/pdf");
    downloadPdfTable({
      title: cfg.title,
      columns: cfg.columns.map((c) => c.header),
      rows: rows.map((r) => cfg.columns.map((c) => exportCellText(c, r))),
      filename: `${cfg.filename}-${stamp}.pdf`,
      subtitle: `${describeFilter(ctx, cfg.note)} · ${rows.length} row${rows.length === 1 ? "" : "s"}`,
    });
    return;
  }
  const { downloadExcel } = await import("@/lib/excel-export");
  await downloadExcel({
    sheetName: cfg.title,
    filename: `${cfg.filename}-${stamp}.xlsx`,
    columns: cfg.columns.map((c) => ({ header: c.header, type: c.type ?? "text", decimals: c.decimals ?? 2 })),
    rows: rows.map((r) => cfg.columns.map((c) => c.value(r) ?? null)),
    about: [
      ["Company", COMPANY_NAME],
      ["List", cfg.title],
      ["Generated", formatDateTime(new Date())],
      ["Generated by", getPdfUser() ?? "—"],
      ["Rows", String(rows.length)],
      ["Filter", describeFilter(ctx, cfg.note)],
    ],
  });
}
