-- ============================================================
-- FB-0002 (Item Master, /items/new):
--   1. "Category should be Raw Material, Packaging and Finished Product" —
--      makes 'processed' a normal, user-creatable/editable category
--      (application-side change in lib/actions/items.ts + item-form.tsx;
--      this migration only changes the DB-side code generator).
--   2. "autogenerated Item Code starting RM/PKG/FP suffixed by autogenerated
--      number ... RM-00001, PKG-00001, FP-00001" — get_next_item_code() was
--      only a 2-way if/else (raw->RM, else->PKG) with 4-digit padding.
--      Rewritten to a 3-way branch (raw->RM, packaging->PKG,
--      processed->FP) with 5-digit padding on all three, using a new
--      sequence for the FP prefix so it doesn't share numbering with
--      RM/PKG.
--   3. "unit selection for Default QC Qty, Default stability qty, default
--      R&D qty (one selection for all three)" — adds
--      items.default_sample_unit, a single unit shared by all three
--      default-sampling-quantity fields, independent of the item's base
--      `unit`. This is deliberately DISPLAY-ONLY for now: it is not wired
--      into purchase_lines' qc_qty/stability_qty/rnd_qty, which still share
--      one `unit` column with `quantity` and feed the generated
--      `remaining_qty` column (quantity - qc_qty - stability_qty -
--      rnd_qty) — automatically converting between units there would need
--      a real unit-conversion table, which doesn't exist anywhere in this
--      schema yet. See the app-side change for how it's surfaced (a
--      "recommended sample" hint on the purchase line form) — flagged in
--      chat as an intentional scope decision, not an oversight.
--
-- Standalone, additive migration. Safe to re-run.
-- ============================================================

create sequence if not exists public.item_code_seq_fp start 1;
grant usage, select on public.item_code_seq_fp to anon, authenticated;

create or replace function public.get_next_item_code(p_category text)
returns text language plpgsql as $$
declare v_num int; v_prefix text;
begin
  if p_category = 'packaging' then
    v_num := nextval('public.item_code_seq_pkg'); v_prefix := 'PKG';
  elsif p_category = 'processed' then
    v_num := nextval('public.item_code_seq_fp'); v_prefix := 'FP';
  else
    v_num := nextval('public.item_code_seq_raw'); v_prefix := 'RM';
  end if;
  return v_prefix || '-' || lpad(v_num::text, 5, '0');
end $$;

alter table public.items add column if not exists default_sample_unit text;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'items_default_sample_unit_check'
  ) then
    alter table public.items
      add constraint items_default_sample_unit_check
      check (default_sample_unit in ('kg','g','mg','ltr','ml','count','bottle','pack'));
  end if;
end $$;
