-- ============================================================
-- Instrument / Equipment Master
--
-- Requested per the open-requirements-log gap analysis (12-13 Sept 2026):
-- spec.md lists "Equipment | Instrument ID, Name, Room No, Section,
-- Calibration Status" as a key master-data entity with no equivalent
-- anywhere in the schema. Software Point.docx separately lists "Instrument
-- ID | Name of instrument and ID no" under Master data.
--
-- Seeded from the real legacy inventory: "ROOM WISE INSTRUMENT AND
-- EQUIPMENT ID DEC 2023 FINAL.xlsx" (Sheet1 only — Sheet2 duplicates Room 7
-- and Sheet3 is an unrelated RM/vendor purchase list, both skipped). Per
-- Ravi (13 Sept 2026): this source data is for reference only, not
-- production-critical, so the two-level "type + individually tagged unit"
-- structure in the source sheet is deliberately flattened to one row per
-- line in the sheet — a bare count with no tag becomes one row with that
-- quantity; a tagged physical unit becomes its own row with quantity 1.
-- `calibration_status` has no equivalent anywhere in the source data (it's
-- a spec.md-only ask) and starts null for every seeded row.
-- ============================================================

create sequence public.equipment_code_seq start 1;

create table public.equipment (
  id uuid primary key default gen_random_uuid(),
  equipment_code text not null unique,
  name text not null,
  room_no text,
  section text,
  legacy_asset_id text,
  quantity numeric not null default 1,
  calibration_status text check (calibration_status in ('calibrated', 'due', 'not_applicable')),
  last_calibration_date date,
  next_calibration_due date,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz,
  updated_by uuid references auth.users(id)
);
create trigger trg_equipment_updated before update on public.equipment
  for each row execute function public.set_updated_at();
alter table public.equipment enable row level security;
create policy equipment_select on public.equipment for select using (public.is_signed_in());
-- Insert/update per Ravi's 13 Sept 2026 decision: broader than the plain
-- master-data default (system_admin/inventory_manager/mfr_manager) —
-- equipment lives across QC and production rooms alike, and calibration
-- status is itself a QC concern, so quality_checker/qc_reviewer are
-- included too. Mirrors MODULE_WRITE_ROLES.equipment in roles.ts.
-- Delete is split out and kept admin-only, matching the convention set in
-- 0009_master_data_delete_policy.sql for every other master-data table
-- (items_delete, vendors_delete) — a deliberate tightening, not something
-- to loosen just because this table's write roles are broader.
create policy equipment_insert on public.equipment for insert
  with check (public.has_any_role('system_admin', 'inventory_manager', 'mfr_manager', 'quality_checker', 'qc_reviewer'));
create policy equipment_update on public.equipment for update
  using (public.has_any_role('system_admin', 'inventory_manager', 'mfr_manager', 'quality_checker', 'qc_reviewer'))
  with check (public.has_any_role('system_admin', 'inventory_manager', 'mfr_manager', 'quality_checker', 'qc_reviewer'));
create policy equipment_delete on public.equipment for delete
  using (public.has_any_role('system_admin'));

create or replace function public.get_next_equipment_code()
returns text language sql as $$
  select 'EQ-' || lpad(nextval('public.equipment_code_seq')::text, 4, '0');
$$;

-- Non-consuming preview, same pattern as peek_next_vendor_code() /
-- peek_next_item_code() in 0012_peek_next_codes.sql.
create or replace function public.peek_next_equipment_code()
returns text language sql stable as $$
  select 'EQ-' || lpad(
    (case when is_called then last_value + 1 else last_value end)::text,
    4, '0'
  )
  from public.equipment_code_seq;
$$;

-- ------------------------------------------------------------
-- One-time seed from the legacy room-wise equipment list (304 rows).
-- equipment_code is assigned here directly (EQ-0001..EQ-0304) rather than
-- via get_next_equipment_code(), so the sequence is advanced to match in
-- the same statement — the first equipment added through the UI after
-- this migration runs will correctly be EQ-0305.
-- ------------------------------------------------------------
insert into public.equipment (equipment_code, name, room_no, section, legacy_asset_id, quantity)
select 'EQ-' || lpad((row_number() over ())::text, 4, '0'), name, room_no, section, legacy_asset_id, quantity
from (values
  ('Hygrometer', '2', 'Raw material section', 'ANHC/QC/02/205(B1)', 1),
  ('Electronic balance', '2', 'Raw material section', 'BSDT/RM/02/150K/037', 1),
  ('Rat cage', '2', 'Raw material section', 'ANHC/GN/02/206(A1-A10)', 1),
  ('Trolley', '2', 'Raw material section', 'ANHC/PD/02/200', 1),
  ('Oil pump', '2', 'Raw material section', 'ANHC/PD/02/225', 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', null, 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', 'ANHC/PD/02/200L/008', 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', 'ANHC/PD/02/200L/009', 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', 'ANHC/PD/02/200L/010', 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', 'ANHC/PD/02/200L/011', 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', 'ANHC/PD/02/200L/012', 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', 'ANHC/PD/02/200L/013', 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', 'ANHC/PD/02/200L/014', 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', 'ANHC/PD/02/200L/015', 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', 'ANHC/PD/02/100L/016', 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', 'ANHC/PD/02/100L/017', 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', 'ANHC/PD/02/100L/018', 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', 'ANHC/PD/02/50L/019', 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', 'ANHC/PD/02/50L/020', 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', 'ANHC/PD/02/50L/021', 1),
  ('Wooden Barrels', '3', 'Asava-arishta section', 'ANHC/PD/02/50L/022', 1),
  ('Storage Vessel sintex (Plastic)', '3', 'Asava-arishta section', null, 1),
  ('Storage Vessel sintex (Plastic)', '3', 'Asava-arishta section', 'BSDT/PD/02/200L/012', 1),
  ('Storage Vessel sintex (Plastic)', '3', 'Asava-arishta section', 'BSDT/PD/02/200L/013', 1),
  ('Storage Vessel sintex (Plastic)', '3', 'Asava-arishta section', 'BSDT/PD/02/200L/014', 1),
  ('Storage Vessel sintex (Plastic)', '3', 'Asava-arishta section', 'BSDT/PD/02/200L/015', 1),
  ('SS Vessel with drain knob', '3', 'Asava-arishta section', null, 1),
  ('SS Vessel with drain knob', '3', 'Asava-arishta section', 'ANHC/PD/150L/148', 1),
  ('SS Vessel with drain knob', '3', 'Asava-arishta section', 'ANHC/PD/150L/149', 1),
  ('Room Heater', '3', 'Asava-arishta section', 'ANHC/PD/02/RH/175', 1),
  ('Hygrometer', '3', 'Asava-arishta section', 'ANHC/QC/02/205(B2)', 1),
  ('SS vessels', '3', 'Asava-arishta section', 'BSDT/PD/80 L/02/109', 1),
  ('SS vessels', '3', 'Asava-arishta section', 'BSDT/PD/80 L/02/110', 1),
  ('Donga (MS)', '3', 'Asava-arishta section', 'ANHC/PD/02/143', 1),
  ('Plastic barrels(storage vessels)', '3', 'Asava-arishta section', null, 1),
  ('Plastic barrels(storage vessels)', '3', 'Asava-arishta section', 'ANHC/PD/02/80L/233', 1),
  ('Plastic barrels(storage vessels)', '3', 'Asava-arishta section', 'ANHC/PD/02/80L/233/A', 1),
  ('Plastic barrels(storage vessels)', '3', 'Asava-arishta section', 'ANHC/PD/02/80L/234', 1),
  ('Plastic barrels(storage vessels)', '3', 'Asava-arishta section', 'ANHC/PD/02/80L/234/A', 1),
  ('Plastic barrels(storage vessels)', '3', 'Asava-arishta section', 'ANHC/PD/02/30L/235', 1),
  ('Plastic barrels(storage vessels)', '3', 'Asava-arishta section', 'ANHC/PD/02/30L/236', 1),
  ('Plastic barrels(storage vessels)', '3', 'Asava-arishta section', 'ANHC/PD/02/30L/236/A', 1),
  ('Plastic measures', '3', 'Asava-arishta section', null, 1),
  ('Plastic measures (5L)', '3', 'Asava-arishta section', null, 1),
  ('Plastic measures (2L)', '3', 'Asava-arishta section', null, 1),
  ('Plastic measures (0.5 L)', '3', 'Asava-arishta section', null, 1),
  ('Hygrometer', '3', 'Capsule section', 'ANHC/QC/03/205(B3)', 1),
  ('Capsule Machine 300 Holes', '3', 'Capsule section', 'ANHC/PD/03/207', 1),
  ('Capsule machine 100 holes', '3', 'Capsule section', null, 1),
  ('Capsule machine 100 holes', '3', 'Capsule section', 'ANHC/PD/03/208', 1),
  ('Capsule machine 100 holes', '3', 'Capsule section', 'ANHC/PD/03/209', 1),
  ('Air Conditioner', '3', 'Capsule section', 'ANHC/PD/03/226', 1),
  ('Label Printing  Machine', '3', 'Capsule section', 'ANHC/PKG/06/191', 1),
  ('Oven', '4', 'Granulation section', null, 1),
  ('Oven', '4', 'Granulation section', 'BSDT/PD/04/N/018', 1),
  ('Oven', '4', 'Granulation section', 'BSDT/PD/04/O/019', 1),
  ('Hygrometer', '4', 'Granulation section', 'ANHC/QC/04/205(B4)', 1),
  ('Multi Mill', '4', 'Granulation section', 'BSDT/PD/04/ML/176', 1),
  ('Mixer', '4', 'Granulation section', 'ANHC/PD/04/R/069', 1),
  ('Hygrometer', '5', 'Tableting section', 'ANHC/QC/05/205(B5)', 1),
  ('Weighing balance', '5', 'Tableting section', 'ANHC/PD/05/600G/177', 1),
  ('Tablet Punching M/C', '5', 'Tableting section', null, 1),
  ('Tablet Punching M/C', '5', 'Tableting section', 'BSDT/PD/05/O/022', 1),
  ('Tablet Punching M/C', '5', 'Tableting section', 'BSDT/PD/05/N/023', 1),
  ('Air blower', '5', 'Tableting section', 'ANHC/PD/05/203', 1),
  ('Wet Grinder', '5', 'Wet Grinding section', null, 1),
  ('Wet Grinder', '5', 'Wet Grinding section', 'BSDT/PD/05/5L/024', 1),
  ('Wet Grinder', '5', 'Wet Grinding section', 'ANHC/PD/05/10L/027', 1),
  ('Wet Grinder', '5', 'Wet Grinding section', 'ANHC/PD/05/5L/028', 1),
  ('Wet Grinder', '5', 'Wet Grinding section', 'ANHC/PD/05/3L/029', 1),
  ('Wet Grinder', '5', 'Wet Grinding section', 'ANHC/PD/05/2L/225', 1),
  ('Stone mortar and pestle', '5', 'Wet Grinding section', 'ANHC/BH/12/083', 1),
  ('SS vessels', '5', 'Wet Grinding section', 'BSDT/PD/BR/20 L/11/118', 1),
  ('Hygrometer', '6', 'Labelling and packing', 'ANHC/QC/06/205(B6)', 1),
  ('Liquid Filling M/C', '6', 'Labelling and packing', 'BSDT/PKG/06/031', 1),
  ('Capping and Sealing M/C', '6', 'Labelling and packing', 'BSDT/PKG/06/N/032', 1),
  ('Electronic Weighing Balance', '6', 'Labelling and packing', 'BSDT/PKG/06/5K/035', 1),
  ('Foot Sealer', '6', 'Labelling and packing', 'BSDT/PKG/06/125', 1),
  ('Foot Sealer', '6', 'Labelling and packing', 'BSDT/PKG/06/126', 1),
  ('Vaccum Pack Machine', '6', 'Labelling and packing', 'BSDT/PKG/06/137', 1),
  ('Vaccum Pack Machine', '6', 'Labelling and packing', 'BSDT/PKG/06/138', 1),
  ('Hand Sealer', '6', 'Labelling and packing', 'ANHC/PKG/06/227', 1),
  ('Hand Sealer', '6', 'Labelling and packing', 'ANHC/PKG/06/228', 1),
  ('Hand Cutter', '6', 'Labelling and packing', 'ANHC/PKG/06/229', 1),
  ('Hand Cutter', '6', 'Labelling and packing', 'ANHC/PKG/06/230', 1),
  ('Electric press', '6', 'Labelling and packing', 'ANHC/PKG/06/231', 1),
  ('Electric press', '6', 'Labelling and packing', 'ANHC/PKG/06/232', 1),
  ('Hot air gun', '6', 'Labelling and packing', 'ANHC/PKG/06/193', 1),
  ('Hot air gun', '6', 'Labelling and packing', 'ANHC/PKG/06/194', 1),
  ('Pouch Sealing machine', '6', 'Labelling and packing', 'ANHC/PKG/06/192', 1),
  ('Shrink tunnel', '6', 'Labelling and packing', 'ANHC/PKG/06/213', 1),
  ('Tablet counter (SS)', '6', 'Labelling and packing', null, 1),
  ('Tablet counter (SS)', '6', 'Labelling and packing', 'ANHC/PKG/06/214', 1),
  ('Tablet counter (SS)', '6', 'Labelling and packing', 'ANHC/PKG/06/214/A', 1),
  ('Tablet counter (SS)', '6', 'Labelling and packing', 'ANHC/PKG/06/215', 1),
  ('Tablet counter (SS)', '6', 'Labelling and packing', 'ANHC/PKG/06/215/A', 1),
  ('Wad sealing machine', '6', 'Labelling and packing', 'ANHC/PKG/06/201', 1),
  ('Particle filling machine', '6', 'Labelling and packing', 'ANHC/PKG/06/196', 1),
  ('Measuring (Plasticware)', '6', 'Labelling and packing', null, 1),
  ('Measuring (Plasticware) (500 ML)', '6', 'Labelling and packing', null, 1),
  ('Measuring (Plasticware) (1 L)', '6', 'Labelling and packing', null, 1),
  ('Measuring (Plasticware) (2 L)', '6', 'Labelling and packing', null, 1),
  ('Measuring (Plasticware) (5 L)', '6', 'Labelling and packing', null, 1),
  ('Measuring (Plasticware) (10 ml)', '6', 'Labelling and packing', null, 1),
  ('SS Trolley', '6', 'Labelling and packing', 'ANHC/PKG/246', 1),
  ('Hygrometer', '7', 'Quality Control', 'ANHC/QC/07/205(B7)', 1),
  ('Electronic balance', '7', 'Quality Control', 'ANHC/QC/07/211', 1),
  ('Lab Oven', '7', 'Quality Control', 'BSDT/QC/07/039', 1),
  ('Friability Apparatus', '7', 'Quality Control', 'BSDT/QC/07/040', 1),
  ('Disintegration Apparatus', '7', 'Quality Control', 'BSDT/QC/07/041', 1),
  ('Hardness Tester', '7', 'Quality Control', 'BSDT/QC/07/042', 1),
  ('Hardness Tester', '7', 'Quality Control', 'BSDT/QC/07/042/A', 1),
  ('Vernier Caliper', '7', 'Quality Control', 'BSDT/QC/07/043', 1),
  ('Microscope', '7', 'Quality Control', 'BSDT/QC/07/045', 1),
  ('Heating Mantle', '7', 'Quality Control', 'BSDT/QC/07/046', 1),
  ('Heating Mantle', '7', 'Quality Control', 'ANHC/QC/07/047', 1),
  ('pH Meter', '7', 'Quality Control', 'BSDT/QC/07/048', 1),
  ('Hot Plate', '7', 'Quality Control', 'BSDT/QC/07/049', 1),
  ('Refractometer', '7', 'Quality Control', 'BSDT/QC/07/050', 1),
  ('Refractometer', '7', 'Quality Control', 'ANHC/QC/07/212', 1),
  ('Water bath', '7', 'Quality Control', 'ANHC/QC/07/051', 1),
  ('Ash Instrument', '7', 'Quality Control', 'ANHC/QC/07/052', 1),
  ('SS working table', '7', 'Quality Control', 'ANHC/QC/07/204', 1),
  ('Mortar and pestle (porcelain)', '7', 'Quality Control', null, 1),
  ('Mortar and pestle (porcelain)', '7', 'Quality Control', 'ANHC/PD/07/L/237', 1),
  ('Mortar and pestle (porcelain)', '7', 'Quality Control', 'ANHC/PD/07/M/238', 1),
  ('Mortar and pestle (porcelain)', '7', 'Quality Control', 'ANHC/PD/07/S/239', 1),
  ('Computer- 2, printer-1 and UPS-2', '7', 'Quality Control', 'ANHC/PD/07/S/240', 1),
  ('Silica crucible', '7', 'Quality Control', null, 1),
  ('Silica crucible (Glass crucuble)', '7', 'Quality Control', null, 1),
  ('Glassware and plasticware', '7', 'Quality Control', 'Assorted', 1),
  ('SS pair of tongs', '7', 'Quality Control', null, 1),
  ('Hygrometer', '8', 'Churna section', 'ANHC/QC/08/205(B8)', 1),
  ('Mixer', '8', 'Churna section', 'ANHC/PD/08/R/068', 1),
  ('Pulverizer MS', '8', 'Churna section', 'BSDT/PD/08/N/053', 1),
  ('Pulverize SS', '8', 'Churna section', 'ANHC/PD/08/195', 1),
  ('Mass mixer SS', '8', 'Churna section', 'ANHC/PD/08/199', 1),
  ('Electronic Weighing Balance', '8', 'Churna section', 'BSDT/BH/08/20K/034', 1),
  ('Vibro Sifter SS', '8', 'Churna section', 'BSDT/PD/08/055', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', null, 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/10#/216', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/12#/217', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/14#/218', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/15#/219', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/16#/056', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/16#/056/A', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/16#/056/B', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/40#/057', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/50#/220', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/60#/058', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/60#/058/A', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/60#/059', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/60#/060', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/80#/061', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/80#/061/A', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/100#/062', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/100#/062/A', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/100#/062/B', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/150#/063', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/150#/064', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/150#/064/A', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/200#/065', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/200#/065/A', 1),
  ('Vibro sifter Sieves SS', '8', 'Churna section', 'BSDT/PD/08/200#/065/C', 1),
  ('Manual Sieves (SS)', '8', 'Churna section', null, 1),
  ('Manual Sieves (SS)', '8', 'Churna section', 'BSDT/PD/08/40#/179', 1),
  ('Manual Sieves (SS)', '8', 'Churna section', 'BSDT/PD/08/40#/180', 1),
  ('Manual Sieves (SS)', '8', 'Churna section', 'BSDT/PD/08/40#/180/A', 1),
  ('Manual Sieves (SS)', '8', 'Churna section', 'BSDT/PD/08/40#/180/B', 1),
  ('Manual Sieves (SS)', '8', 'Churna section', 'BSDT/PD/08/40#/180/C', 1),
  ('Manual Sieves (SS)', '8', 'Churna section', 'BSDT/PD/08/22#/182', 1),
  ('Manual Sieves (SS)', '8', 'Churna section', 'BSDT/PD/08/22#/183', 1),
  ('Manual Sieves (SS)', '8', 'Churna section', 'BSDT/PD/08/22#/184', 1),
  ('Manual Sieves (SS)', '8', 'Churna section', 'BSDT/PD/08/22#/185', 1),
  ('Manual Sieves (SS)', '8', 'Churna section', 'BSDT/PD/08/15#/188', 1),
  ('Manual Sieves (SS)', '8', 'Churna section', 'BSDT/PD/08/15#/188/A', 1),
  ('Manual Sieves (SS)', '8', 'Churna section', 'BSDT/PD/06/11#/186', 1),
  ('Manual Sieves (SS)', '8', 'Churna section', 'BSDT/PD/06/11#/186/A', 1),
  ('Manual Sieves (SS)', '8', 'Churna section', 'BSDT/PD/06/16#/187', 1),
  ('Hygrometer', '9', 'Avaleha section', 'ANHC/QC/09/205(B9)', 1),
  ('Avaleha Making M/C', '9', 'Avaleha section', 'BSDT/PD/09/A/071', 1),
  ('Avaleha Making M/C', '9', 'Avaleha section', 'ANHC/PD/09/C/210', 1),
  ('SS vessels', '9', 'Avaleha section', 'BSDT/PD/BR/80 L/11/111', 1),
  ('Fly catcher (UV)', '9', 'Avaleha section', 'ANHC/PD/09/233', 1),
  ('Hygrometer', '10', 'Tail-Ghrut section', 'ANHC/QC/10/205(B10)', 1),
  ('Gas burners', '10', 'Tail-Ghrut section', 'BSDT/PD/S/10/136 (Single)', 1),
  ('Gas burners', '10', 'Tail-Ghrut section', 'ANHC/PD/S/10/130(Double)', 1),
  ('Vessel with lids (SS and Brass)', '10', 'Tail-Ghrut section', 'ANHC/PD/50 L/10/113', 1),
  ('Vessel with lids (SS and Brass)', '10', 'Tail-Ghrut section', 'BSDT/PD/BR/30 L/10/116', 1),
  ('Vessel with lids (SS and Brass)', '10', 'Tail-Ghrut section', 'BSDT/PD/BR/30 L/10/117', 1),
  ('Laser Gun', '10', 'Tail-Ghrut section', 'BSDT/BH/08/LG/172/A', 1),
  ('Hygrometer', '11', 'Bhatti section', 'ANHC/QC/11/205(B11)', 1),
  ('Gas burners', '11', 'Bhatti section', 'BSDT/KH/11/134(Triple)', 1),
  ('Gas burners', '11', 'Bhatti section', 'BSDT/KH/11/135(Single)', 1),
  ('SS Vessels', '11', 'Bhatti section', 'ANHC/PD/200 L/11/105', 1),
  ('SS Vessels', '11', 'Bhatti section', 'ANHC/PD/200 L/11/106', 1),
  ('SS Vessels', '11', 'Bhatti section', 'ANHC/PD/100 L/11/107', 1),
  ('SS Vessels', '11', 'Bhatti section', 'BSDT/PD/BR/50 L/11/112', 1),
  ('Fire extinguisher (TYPE A,B.C)', '11', 'Bhatti section', 'BSDT/PD/5kg/241', 1),
  ('Hygrometer', '12', 'Bhasma section', 'ANHC/QC/12/205(B12)', 1),
  ('Ball Mill', '12', 'Bhasma section', 'ANHC/PD/12/147', 1),
  ('Lemon Juicer', '12', 'Bhasma section', 'ANHC/PD/12/145', 1),
  ('Lemon Juicer', '12', 'Bhasma section', 'ANHC/BH/12/146', 1),
  ('Gas burners', '12', 'Bhasma section', 'BSDT/BH/B/12/131(Double)', 1),
  ('Gas burners', '12', 'Bhasma section', 'BSDT/KH/12/132(Single)', 1),
  ('Gas burners', '12', 'Bhasma section', 'BSDT/KH/12/133(Single)', 1),
  ('Mortar and Pestle (Stone)', '12', 'Bhasma section', 'BSDT/BH/12/BCB/073', 1),
  ('Mortar and Pestle (Stone)', '12', 'Bhasma section', 'BSDT/BH/12/BCB/074', 1),
  ('Mortar and Pestle (Stone)', '12', 'Bhasma section', 'BSDT/BH/12/OB/075', 1),
  ('Mortar and Pestle (Stone)', '12', 'Bhasma section', 'BSDT/BH/12/OS/076', 1),
  ('Mortar and Pestle (Stone)', '12', 'Bhasma section', 'BSDT/BH/12/BCM/077', 1),
  ('Mortar and Pestle (Stone)', '12', 'Bhasma section', 'BSDT/BH/12/BCS/078', 1),
  ('Mortar and Pestle (Stone)', '12', 'Bhasma section', 'BSDT/BH/12/BCS/079', 1),
  ('Mortar and Pestle (Stone)', '12', 'Bhasma section', 'BSDT/BH/12/BCS/080', 1),
  ('Mortar and Pestle (Stone)', '12', 'Bhasma section', 'BSDT/BH/12/OEX/081', 1),
  ('Mortar and Pestle (Stone)', '12', 'Bhasma section', 'ANHC/BH/12/082', 1),
  ('Puta - 17', '12', 'Bhasma section', null, 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/086', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/087', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/088', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/089', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/090', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/091', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/092', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/093', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/094', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/095', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/096', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/097', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/098', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/099', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/100', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/101', 1),
  ('Puta - 17', '12', 'Bhasma section', 'BSDT/BH/12/102', 1),
  ('Electronic Weighing Balance', '12', 'Bhasma section', 'BSDT/BH/12/20K/034', 1),
  ('Wet Grinder', '12', 'Bhasma section', 'BSDT/BH/12/3L/025', 1),
  ('Wet Grinder', '12', 'Bhasma section', 'BSDT/BH/12/2L/026', 1),
  ('Wet Grinder', '12', 'Bhasma section', 'ANHC/BH/12/10L/030', 1),
  ('Wet Grinder', '12', 'Bhasma section', 'BSDT/BH/12/5L/150', 1),
  ('Wet Grinder', '12', 'Bhasma section', 'ANHC/BH/12/2L/151', 1),
  ('Wet Grinder', '12', 'Bhasma section', 'ANHC/BH/12/2L/152', 1),
  ('Wet Grinder', '12', 'Bhasma section', 'ANHC/PD/12/2L/202', 1),
  ('Pyrometer', '12', 'Bhasma section', 'BSDT/BH/DLS1/12/086A/164', 1),
  ('Pyrometer', '12', 'Bhasma section', 'BSDT/BH/DLS1//12/086B/164', 1),
  ('Pyrometer', '12', 'Bhasma section', 'BSDT/BH/DLS1/12/086C/164', 1),
  ('Pyrometer', '12', 'Bhasma section', 'BSDT/BH/DLS1/12/088A/165', 1),
  ('Pyrometer', '12', 'Bhasma section', 'BSDT/BH/DLS1/12/088B/165', 1),
  ('Pyrometer', '12', 'Bhasma section', 'BSDT/BH/DLS1/12/088C/165', 1),
  ('Pyrometer', '12', 'Bhasma section', 'BSDT/BH/DSL2/12/091/166', 1),
  ('Pyrometer', '12', 'Bhasma section', 'BSDT/BH/DSL2/12/092/167', 1),
  ('Pyrometer', '12', 'Bhasma section', 'BSDT/BH/DSL2/12/093/168', 1),
  ('Pyrometer', '12', 'Bhasma section', 'BSDT/BH/DSL2/12/094/169', 1),
  ('Pyrometer', '12', 'Bhasma section', 'BSDT/BH/DSL2/12/095/170', 1),
  ('Pyrometer', '12', 'Bhasma section', 'BSDT/BH/DSL2/12/096/171', 1),
  ('Laser Gun', '12', 'Bhasma section', 'BSDT/BH/08/LG/12/172/A', 1),
  ('Sieves with lid and collector', '12', 'Bhasma section', 'BSDT/BH/12/200#/189', 1),
  ('Sieves with lid and collector', '12', 'Bhasma section', 'BSDT/BH/12/200#/190', 1),
  ('Palika Yantra/ Donga', '12', 'Bhasma section', 'ANHC/PD/12/144', 1),
  ('SS Vessels', '12', 'Bhasma section', 'BSDT/BH/50 L/12/114', 1),
  ('SS Vessels', '12', 'Bhasma section', 'ANHC/BH/50 L /12/115', 1),
  ('SS Vessels', '12', 'Bhasma section', 'ANHC/BH/15L/12/119', 1),
  ('SS Vessels', '12', 'Bhasma section', 'ANHC/BH/10L/12/121', 1),
  ('SS Vessels', '12', 'Bhasma section', 'ANHC/BH/10L/12/122', 1),
  ('Iron Vessel(Kadhai) Big', '12', 'Bhasma section', null, 1),
  ('Iron Vessel(Kadhai) Big', '12', 'Bhasma section', 'BSDT/PD/12/139', 1),
  ('Iron Vessel(Kadhai) Big', '12', 'Bhasma section', 'BSDT/PD/12/139/A', 1),
  ('Iron Vessel(Kadhai) Small', '12', 'Bhasma section', null, 1),
  ('Iron Vessel(Kadhai) Small', '12', 'Bhasma section', 'BSDT/PD/12/MS/140', 1),
  ('Iron Vessel(Kadhai) Small', '12', 'Bhasma section', 'BSDT/PD/12/MS/140/A', 1),
  ('Iron Vessel(Kadhai) Small', '12', 'Bhasma section', 'BSDT/PD/12/MS/140/B', 1),
  ('Iron Vessel(Kadhai) Small', '12', 'Bhasma section', 'BSDT/PD/12/MS/140/C', 1),
  ('Iron Vessel(Kadhai) Small', '12', 'Bhasma section', 'BSDT/PD/12/SS/221', 1),
  ('Iron Vessel(Kadhai) Small', '12', 'Bhasma section', 'BSDT/PD/12/SS/222', 1),
  ('Iron Vessel(Kadhai) Small', '12', 'Bhasma section', 'BSDT/PD/12/AL/223', 1),
  ('Iron Vessel(Kadhai) Small', '12', 'Bhasma section', 'BSDT/PD/12/AL/224', 1),
  ('Hand Sieves', '12', 'Bhasma section', null, 1),
  ('Hand Sieves', '12', 'Bhasma section', 'BSDT/BH/12/22#/181', 1),
  ('Hand Sieves', '12', 'Bhasma section', 'BSDT/BH/12/15#/188/B', 1),
  ('Hand Sieves', '12', 'Bhasma section', 'BSDT/PD/06/16#/187/A', 1),
  ('Hand Sieves', '12', 'Bhasma section', 'BSDT/PD/06/16#/187/B', 1),
  ('Hand Sieves', '12', 'Bhasma section', 'BSDT/BH/12/40#/178', 1),
  ('Mechanical Khal', '12', 'Bhasma section', 'BSDT/BH/12/084 (Khal Batta)', 1),
  ('Mechanical Khal', '12', 'Bhasma section', 'BSDT/PD/12/085 (Khal Batta)', 1),
  ('Cylindrical vessel', '12', 'Bhasma section', null, 1),
  ('Cylindrical vessel', '12', 'Bhasma section', 'ANHC/BH/CV/6L/123', 1),
  ('Cylindrical vessel', '12', 'Bhasma section', 'ANHC/BH/CV/5L/123/A', 1),
  ('Cylindrical vessel', '12', 'Bhasma section', 'ANHC/BH/CV/5L/123/B', 1),
  ('Cylindrical vessel', '12', 'Bhasma section', 'ANHC/BH/CV/5L/123/C', 1),
  ('Cylindrical vessel', '12', 'Bhasma section', 'ANHC/BH/CV/5L/123/D', 1),
  ('Cylindrical vessel', '12', 'Bhasma section', 'ANHC/BH/CV/5L/123/D', 1),
  ('Cylindrical vessel', '12', 'Bhasma section', 'ANHC/BH/CV/2L/124', 1),
  ('Cylindrical vessel', '12', 'Bhasma section', 'ANHC/BH/CV/2L/124/A', 1),
  ('Cylindrical vessel', '12', 'Bhasma section', 'ANHC/BH/CV/2L/124/B', 1),
  ('Cylindrical vessel', '12', 'Bhasma section', 'ANHC/BH/CV/2L/124/C', 1),
  ('Fire extinguisher (TYPE A,B.C)', '12', 'Bhasma section', 'BSDT/BH/5kg/243', 1),
  ('RO System room', null, 'Common', 'BSDT/RO/128', 1),
  ('SS Water Tank', null, 'Common', 'BSDT/RO/129', 1),
  ('Book Shelf (Library)', null, 'Common', 'BSDT/PD/04/021', 1),
  ('Refrigerator with stabilizer', null, 'Common', 'ANHC/PD/235L/244', 1),
  ('RO Water dispenser', null, 'Common', 'ANHC/PD/20L./245', 1),
  ('Fire extinguisher (TYPE A,B.C)', null, 'Common', 'BSDT/PD/5kg/243', 1),
  ('Fire extinguisher (TYPE A,B.C)', null, 'Common', 'BSDT/PD/5kg/243/A', 1),
  ('Fire extinguisher (TYPE A,B.C)', null, 'Common', 'BSDT/PD/5kg/243/B', 1),
  ('Fire extinguisher (TYPE A,B.C)', null, 'Common', 'BSDT/PD/5kg/243/C', 1)
) as seed(name, room_no, section, legacy_asset_id, quantity);

select setval('public.equipment_code_seq', (select count(*) from public.equipment), true);
