-- ============================================================
-- Certificate of Analysis — templates, step 1 of 2.
--
-- Ravi (22 Sept 2026), via two sample COAs (Raw Material and Finished
-- Product): "let's create functionality to generate certificate of
-- analysis... There is one template per Item Type. First step would be to
-- define Certificate of Analysis steps per item type... Once Item Type is
-- selected, user will get input form to enter Test and Specification.
-- Serial number will be autogenerated (similar to Manufacturing Process
-- entry form in MFR). Once submitted, user will also have option to edit
-- this."
--
-- This migration is template management only (a Test/Specification list
-- per item type) — generating an actual certificate against a batch, with
-- real results and a pixel-matched PDF, is step 2, a separate migration
-- extending coa_records once this is confirmed working.
--
-- Design, deliberately mirroring mfr_procedure_steps/update_mfr_procedure
-- (0048_mfr_procedure.sql) — the exact pattern Ravi pointed at:
--   - One template per item_type_id (unique constraint) — item_types is
--     already the one taxonomy shared by both Raw Material items
--     (items.item_type_id) and Finished Product recipes
--     (mfr_definitions.item_type_id), so this one column resolves either
--     subject to the right template at generation time.
--   - Lines are a child table with a `seq` column (the auto-numbered
--     S.No.), replaced in place on every edit via a security definer RPC
--     (delete-and-reinsert in one transaction) — same "no versioning,
--     edit in place" precedent as update_mfr_recipe()/
--     update_mfr_procedure(), and the same choice Ravi already made for
--     MFR recipes ("we will add versioning if required but right now
--     let's not have this as standard feature").
--   - Write access reuses the existing "coa" role set already granted on
--     coa_records (system_admin, quality_checker, qc_reviewer) — this is
--     the same module, just its template-setup half.
-- ============================================================

create table public.coa_templates (
  id uuid primary key default gen_random_uuid(),
  item_type_id uuid not null unique references public.item_types(id),
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz,
  updated_by uuid references auth.users(id)
);
create trigger trg_coa_templates_updated before update on public.coa_templates
  for each row execute function public.set_updated_at();

create table public.coa_template_lines (
  id uuid primary key default gen_random_uuid(),
  coa_template_id uuid not null references public.coa_templates(id) on delete cascade,
  seq integer not null,
  test text not null,
  specification text not null
);
create index coa_template_lines_template_idx on public.coa_template_lines (coa_template_id, seq);

alter table public.coa_templates enable row level security;
alter table public.coa_template_lines enable row level security;

create policy coa_templates_select on public.coa_templates for select using (public.is_signed_in());
create policy coa_templates_write on public.coa_templates for all
  using (public.has_any_role('system_admin', 'quality_checker', 'qc_reviewer'))
  with check (public.has_any_role('system_admin', 'quality_checker', 'qc_reviewer'));

create policy coa_template_lines_select on public.coa_template_lines for select using (public.is_signed_in());
-- Lines are only ever written via upsert_coa_template() (security definer,
-- below) — no direct client insert/update/delete, same "the RPC is the
-- only writer" shape as mfr_procedure_steps (that table has no write
-- policy of its own either, relying entirely on update_mfr_procedure()).

-- ------------------------------------------------------------
-- upsert_coa_template() — one call creates the template row (if this is
-- the item type's first template) or reuses the existing one, then
-- replaces its lines in place. Mirrors update_mfr_procedure()'s
-- delete-and-reinsert shape; unlike that function, at least one line is
-- required (a template with zero tests isn't a usable template — Ravi's
-- "input form to enter Test and Specification" implies real content),
-- and seq is always renumbered 1..N from the submitted order, matching
-- "Serial number will be autogenerated."
-- ------------------------------------------------------------
create or replace function public.upsert_coa_template(
  p_item_type_id uuid,
  p_lines jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_template_id uuid;
  v_line jsonb;
  v_idx int := 0;
begin
  if not public.has_any_role('system_admin', 'quality_checker', 'qc_reviewer') then
    raise exception 'Not authorized to manage Certificate of Analysis templates.';
  end if;

  if p_item_type_id is null then
    raise exception 'Item type is required.';
  end if;
  if p_lines is null or jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then
    raise exception 'At least one test is required.';
  end if;

  insert into public.coa_templates (item_type_id, created_by)
  values (p_item_type_id, auth.uid())
  on conflict (item_type_id) do update
    set updated_at = now(), updated_by = auth.uid()
  returning id into v_template_id;

  delete from public.coa_template_lines where coa_template_id = v_template_id;

  for v_line in select * from jsonb_array_elements(p_lines)
  loop
    v_idx := v_idx + 1;
    if (v_line->>'test') is null or v_line->>'test' = ''
       or (v_line->>'specification') is null or v_line->>'specification' = '' then
      raise exception 'Row %: both Test and Specification are required.', v_idx;
    end if;
    insert into public.coa_template_lines (coa_template_id, seq, test, specification)
    values (v_template_id, v_idx, v_line->>'test', v_line->>'specification');
  end loop;

  return v_template_id;
end $$;

-- No explicit grant needed — 0001_init.sql's `alter default privileges ...
-- grant execute on functions to anon, authenticated` already covers every
-- function created after it (same closing note as 0037/0041/0048).
